---
title: "SFPA Team ELO Ratings"
author: "Skip Perry"
date: "3/15/2019"
output: github_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(lubridate)

source("02_data_clean.R")
```

```{r}
# Data frame of players and team names in Spring 2019 - helper for next helper function
players_by_team_19 <- 
  bind_rows(
    results_19_no_forfeits %>% transmute(player = home, team = home_team),
    results_19_no_forfeits %>% transmute(player = away, team = away_team)
  ) %>% 
    distinct() %>% 
    arrange(team, player)

# Helper function to add team names to a data frame containing a column for player
append_team_names <- function(df) {
  df %>% 
    full_join(players_by_team_19, by = "player")
}

# Helper function to get player list
full_player_list <- function(df) {
  bind_rows(
    df %>% transmute(player = home), 
    df %>% transmute(player = away)
  ) %>% 
    distinct(player) %>% 
    arrange(player)
}

# Helper function for ELO match win probability
match_win_probability <- function(player_of_interest, home_rating, away_rating) {
  if (player_of_interest == "home") {
    prob <- 1 / (1 + 10 ^ ((away_rating - home_rating) / 400))
  } else {
    prob <- 1 / (1 + 10 ^ ((home_rating - away_rating) / 400))
  }
  prob
}

# Helper function to get a player's rating
get_rating <- function(player_name, ratings_df) {
  ratings_df %>% 
    filter(player == player_name) %>% 
    pull(rating)
}

# Helper function to get K from game count
get_K <- function(player_name, game_count_df, numerator_param) {
  num_games <- 
    game_count_df %>% 
    filter(player == player_name) %>% 
    pull(game_count)
  
  numerator_param / (num_games + 5) ^ 0.4
}
```

```{r}
test_numerator_parameter <- function(numerator_param) {
  # Construct summary data frame of base 1500 ratings using the distinct players seen in the time period
  elo_ratings <-
    full_player_list(results_no_forfeits) %>% 
    mutate(rating = 1500)
  
  # Construct game counter for use in K calculations
  game_counts <-
    full_player_list(results_no_forfeits) %>% 
    mutate(game_count = 0)
  
  # Update the ratings table
  for (i in 1:nrow(results_no_forfeits)) {
    player1 <- results_no_forfeits$home[i]
    player2 <- results_no_forfeits$away[i]
    player1_rating <- get_rating(player1, elo_ratings)
    player2_rating <- get_rating(player2, elo_ratings)
    results_no_forfeits$p1_start_rating[i] <- player1_rating
    results_no_forfeits$p2_start_rating[i] <- player2_rating
    player1_expected <- 1 / (1 + 10 ^ ((player2_rating - player1_rating) / 400))
    player2_expected <- 1 - player1_expected
    winner <- results_no_forfeits$game_winner[i]
    S1 <- ifelse(winner == "home", 1, 0)
    S2 <- ifelse(winner == "home", 0, 1)
    K1 <- get_K(player_name = player1, game_count_df = game_counts, numerator_param = numerator_param)
    K2 <- get_K(player_name = player2, game_count_df = game_counts, numerator_param = numerator_param)
    player1_rating_new = player1_rating + K1 * (S1 - player1_expected)
    player2_rating_new = player2_rating + K2 * (S2 - player2_expected)
    elo_ratings$rating[elo_ratings$player == player1] <- player1_rating_new
    elo_ratings$rating[elo_ratings$player == player2] <- player2_rating_new
    results_no_forfeits$p1_end_rating[i] <- player1_rating_new
    results_no_forfeits$p2_end_rating[i] <- player2_rating_new
    game_counts$game_count[game_count$player == player1] <- 
      game_counts$game_count[game_count$player == player1] + 1
    game_counts$game_count[game_count$player == player2] <- 
      game_counts$game_count[game_count$player == player2] + 1
  }
  
  #elo_ratings %>% 
  #  mutate(rating = round(rating)) %>% 
  #  arrange(-rating) %>% 
  #  append_team_names()
  
  #game_counts %>% 
  #  arrange(-game_count)
  
  matches_with_probabilities <- 
    results_no_forfeits %>% 
    transmute(
      match_date, 
      home, 
      away,
      home_rating = p1_start_rating,
      away_rating = p2_start_rating,
      home_win_prob = 1 / (1 + 10 ^ ((away_rating - home_rating) / 400)),
      home_win = if_else(game_winner == "home", 1, 0)
    )
  
  metrics_df <- 
    matches_with_probabilities %>% 
    transmute(
      match_date,
      home_win,
      home_win_predicted = if_else(home_win_prob >= 0.5, 1, 0),
      home_win_prob,
      prob = round(home_win_prob * 20) / 20
    ) %>% 
    filter(match_date > "2018-03-01")
  
  metrics_df %>% 
    mutate(
      correct_prediction = if_else(home_win == home_win_predicted, 1, 0),
      log_loss = home_win * log(home_win_prob) + (1 - home_win) * log(1 - home_win_prob),
      higher_ranked_prob = if_else(home_win_prob >= 0.5, home_win_prob, 1 - home_win_prob),
      higher_ranked_winner = case_when(
        home_win_prob >= 0.5 & home_win == 1 ~ 1,
        home_win_prob < 0.5 & home_win == 0 ~ 1,
        TRUE ~ 0
      )
    ) %>% 
    summarize(
      accuracy = mean(correct_prediction),
      log_loss = -mean(log_loss),
      calibration = sum(higher_ranked_prob) / sum(higher_ranked_winner),
      discrimination = 
        sum(higher_ranked_prob * higher_ranked_winner) / sum(higher_ranked_winner) - 
        sum(higher_ranked_prob * (1 - higher_ranked_winner)) / sum(1 - higher_ranked_winner)
    ) %>% 
    gather(key = metric, value = value, accuracy:discrimination) %>% 
    mutate(numerator_param = numerator_param)
}
```

```{r}
test_results <- 
  map_dfr(seq(0, 100, by = 5), test_numerator_parameter)

test_results2 <-
  map_dfr(seq(105, 125, by = 5), test_numerator_parameter)
  
test_results
test_numerator_parameter(50)
```

```{r}
bind_rows(test_results, test_results2) %>% 
  filter(metric != "discrimination") %>% 
  ggplot(aes(x = numerator_param, y = value, group = metric, color = metric)) +
  geom_line() +
  geom_point()
```

```{r}
test_results %>% 
  filter(numerator_param == 100)
```

```{r}
apply_elo_ratings <- function(numerator_param) {
  elo_ratings <-
    full_player_list(results_no_forfeits) %>% 
    mutate(rating = 1500)
  
  # Construct game counter for use in K calculations
  game_counts <-
    full_player_list(results_no_forfeits) %>% 
    mutate(game_count = 0)
  
  # Update the ratings table
  for (i in 1:nrow(results_no_forfeits)) {
    player1 <- results_no_forfeits$home[i]
    player2 <- results_no_forfeits$away[i]
    player1_rating <- get_rating(player1, elo_ratings)
    player2_rating <- get_rating(player2, elo_ratings)
    results_no_forfeits$p1_start_rating[i] <- player1_rating
    results_no_forfeits$p2_start_rating[i] <- player2_rating
    player1_expected <- 1 / (1 + 10 ^ ((player2_rating - player1_rating) / 400))
    player2_expected <- 1 - player1_expected
    winner <- results_no_forfeits$game_winner[i]
    S1 <- ifelse(winner == "home", 1, 0)
    S2 <- ifelse(winner == "home", 0, 1)
    K1 <- get_K(player_name = player1, game_count_df = game_counts, numerator_param = numerator_param)
    K2 <- get_K(player_name = player2, game_count_df = game_counts, numerator_param = numerator_param)
    player1_rating_new = player1_rating + K1 * (S1 - player1_expected)
    player2_rating_new = player2_rating + K2 * (S2 - player2_expected)
    elo_ratings$rating[elo_ratings$player == player1] <- player1_rating_new
    elo_ratings$rating[elo_ratings$player == player2] <- player2_rating_new
    results_no_forfeits$p1_end_rating[i] <- player1_rating_new
    results_no_forfeits$p2_end_rating[i] <- player2_rating_new
    game_counts$game_count[game_count$player == player1] <- 
      game_counts$game_count[game_count$player == player1] + 1
    game_counts$game_count[game_count$player == player2] <- 
      game_counts$game_count[game_count$player == player2] + 1
  }
  
  elo_ratings %>% 
    mutate(rating = round(rating)) %>% 
    arrange(-rating)
}
```

```{r}
apply_elo_ratings(numerator_param = 100)
```

```{r}
get_match_probabilities <- function(numerator_param) {
  # Construct summary data frame of base 1500 ratings using the distinct players seen in the time period
  elo_ratings <-
    full_player_list(results_no_forfeits) %>% 
    mutate(rating = 1500)
  
  # Construct game counter for use in K calculations
  game_counts <-
    full_player_list(results_no_forfeits) %>% 
    mutate(game_count = 0)
  
  # Update the ratings table
  for (i in 1:nrow(results_no_forfeits)) {
    player1 <- results_no_forfeits$home[i]
    player2 <- results_no_forfeits$away[i]
    player1_rating <- get_rating(player1, elo_ratings)
    player2_rating <- get_rating(player2, elo_ratings)
    results_no_forfeits$p1_start_rating[i] <- player1_rating
    results_no_forfeits$p2_start_rating[i] <- player2_rating
    player1_expected <- 1 / (1 + 10 ^ ((player2_rating - player1_rating) / 400))
    player2_expected <- 1 - player1_expected
    winner <- results_no_forfeits$game_winner[i]
    S1 <- ifelse(winner == "home", 1, 0)
    S2 <- ifelse(winner == "home", 0, 1)
    K1 <- get_K(player_name = player1, game_count_df = game_counts, numerator_param = numerator_param)
    K2 <- get_K(player_name = player2, game_count_df = game_counts, numerator_param = numerator_param)
    player1_rating_new = player1_rating + K1 * (S1 - player1_expected)
    player2_rating_new = player2_rating + K2 * (S2 - player2_expected)
    elo_ratings$rating[elo_ratings$player == player1] <- player1_rating_new
    elo_ratings$rating[elo_ratings$player == player2] <- player2_rating_new
    results_no_forfeits$p1_end_rating[i] <- player1_rating_new
    results_no_forfeits$p2_end_rating[i] <- player2_rating_new
    game_counts$game_count[game_count$player == player1] <- 
      game_counts$game_count[game_count$player == player1] + 1
    game_counts$game_count[game_count$player == player2] <- 
      game_counts$game_count[game_count$player == player2] + 1
  }
  
  #elo_ratings %>% 
  #  mutate(rating = round(rating)) %>% 
  #  arrange(-rating) %>% 
  #  append_team_names()
  
  #game_counts %>% 
  #  arrange(-game_count)
  
  results_no_forfeits %>% 
    transmute(
      match_date, 
      home, 
      away,
      home_rating = p1_start_rating,
      away_rating = p2_start_rating,
      home_win_prob = 1 / (1 + 10 ^ ((away_rating - home_rating) / 400)),
      home_win = if_else(game_winner == "home", 1, 0)
    )

}
```

```{r}
match_probs <- 
  get_match_probabilities(numerator_param = 100)
```

```{r}
match_probs %>% 
  transmute(
    match_date,
    home_win,
    home_win_predicted = if_else(home_win_prob >= 0.5, 1, 0),
    home_win_prob,
    prob = round(home_win_prob * 20) / 20
  ) %>% 
  filter(match_date > "2018-03-01") %>% 
  group_by(prob) %>% 
  summarize(
    mean_home_win = mean(home_win),
    sd_home_win = sd(home_win),
    n = n()
  ) %>% 
  mutate(
    se_home_win = sd_home_win / n,
    lowci = mean_home_win - qt(0.995, n - 1) * se_home_win,
    highci = mean_home_win + qt(0.995, n - 1) * se_home_win
  ) %>% 
  ggplot(aes(x = prob)) +
  geom_abline(slope = 1, yintercept = 0, color = "white", size = 2) + 
  geom_line(aes(y = lowci), color = "blue", alpha = 0.5) + 
  geom_line(aes(y = highci), color = "blue", alpha = 0.5) + 
  geom_line(aes(y = mean_home_win)) + 
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1))
  
qt(0.975, 600)
?qt
```







```{r}
metrics_df %>% 
  mutate(
    
  ) %>% 
  summarize(log_loss = -mean(log_loss))
```

```{r}
# Set K based on optimization
K_team <- 4

# Data frame of all team names for all seasons
team_names <- 
  bind_rows(
    results_no_forfeits %>% transmute(team = home_team),
    results_no_forfeits %>% transmute(team = away_team)
  ) %>% 
  distinct() %>% 
  arrange(team)

# Data frame of team names in the current Spring 2019 season
team_names_2019 <- 
  bind_rows(
    results_19_no_forfeits %>% transmute(team = home_team),
    results_19_no_forfeits %>% transmute(team = away_team)
  ) %>% 
  distinct() %>% 
  arrange(team)

# Helper function for ELO match win probability
match_win_probability <- function(team_of_interest, home_rating, away_rating, home_advantage) {
  if (team_of_interest == "home") {
    prob <- 1 / (1 + 10 ^ ((away_rating - (home_rating + home_advantage)) / 400))
  } else {
    prob <- 1 / (1 + 10 ^ (((home_rating + home_advantage) - away_rating) / 400))
  }
  prob
}

# Helper function to get a team's rating
get_team_rating <- function(team_name, ratings_df) {
  ratings_df %>% 
    filter(team == team_name) %>% 
    pull(rating)
}

# Initialize ratings at 1500
elo_team_ratings <-
  team_names %>% 
  mutate(rating = 1500)

# Populate real-time match ratings throughout results data frame
for (i in 1:nrow(results_no_forfeits)) {
  team1 <- results_no_forfeits$home_team[i]
  team2 <- results_no_forfeits$away_team[i]
  team1_rating <- get_team_rating(team1, elo_team_ratings)
  team2_rating <- get_team_rating(team2, elo_team_ratings)
  results_no_forfeits$t1_start_rating[i] <- team1_rating
  results_no_forfeits$t2_start_rating[i] <- team2_rating
  team1_expected <-
    match_win_probability(
      team_of_interest = "home", home_rating = team1_rating, away_rating = team2_rating,
      home_advantage = home_advantage
    )
  team2_expected <-
    match_win_probability(
      team_of_interest = "away", home_rating = team1_rating, away_rating = team2_rating,
      home_advantage = home_advantage
    )
  winner <- results_no_forfeits$game_winner[i]
  S1 <- ifelse(winner == "home", 1, 0)
  S2 <- ifelse(winner == "home", 0, 1)
  team1_rating_new <- team1_rating + K_team * (S1 - team1_expected)
  team2_rating_new <- team2_rating + K_team * (S2 - team2_expected)
  elo_team_ratings$rating[elo_team_ratings$team == team1] <- team1_rating_new
  elo_team_ratings$rating[elo_team_ratings$team == team2] <- team2_rating_new
  results_no_forfeits$t1_end_rating[i] <- team1_rating_new
  results_no_forfeits$t2_end_rating[i] <- team2_rating_new
}

elo_team_ratings %>% 
  inner_join(team_names_2019, by = "team") %>% 
  mutate(rating = round(rating)) %>% 
  arrange(-rating)
```

```{r}
latest_match_date <- 
  results_no_forfeits %>% 
  pull(match_date) %>% 
  max()

saveRDS(elo_ratings, str_c("other_data/elo_ratings_", latest_match_date, ".Rdata"))
saveRDS(elo_team_ratings, str_c("other_data/elo_team_ratings_", latest_match_date, ".Rdata"))
saveRDS(results_no_forfeits, str_c("match_data/results_no_forfeits_", latest_match_date, ".Rdata"))
```

```{r}

```

