---
title: "SFPA Fargo Ratings v.3"
author: "Skip Perry"
date: "April 2019"
output: github_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

latest_results_date <- 
  list.files("match_data", pattern = "results_no_forfeits") %>% 
  str_extract("\\d+-\\d+-\\d+") %>% 
  max()

#latest_results_date <- "2019-03-12"

results_no_forfeits_path <-
  str_c("match_data/results_no_forfeits_", latest_results_date, ".Rdata")

results_no_forfeits <- 
  results_no_forfeits_path %>% 
  read_rds()

#results_19_no_forfeits <- 
#  results_no_forfeits %>% 
#  filter(season == "Spring 2019")
```

```{r}
#player_list <- 
#  bind_rows(
#    results_no_forfeits %>% transmute(player = home), 
#    results_no_forfeits %>% transmute(player = away)
#  ) %>% 
#  distinct() %>% 
#  arrange(player)

#date_list <- 
#  results_no_forfeits %>% 
#  select(match_date) %>% 
#  distinct() %>% 
#  pull()
```

```{r}
get_updated_rating <- function(player_of_interest, results_df, ratings_df, a) {
  game_count <- 
    results_df %>% 
    filter(away == player_of_interest | home == player_of_interest) %>% 
    count() %>% 
    pull()
  
  if (game_count == 0) {
    return(ratings_df$rating[ratings_df$player == player_of_interest])
  }
  
  b <- (a - 1) / 500

  results_df %>% 
    filter(away == player_of_interest | home == player_of_interest) %>% 
    transmute(
      season,
      player = player_of_interest,
      opponent = if_else(home == player_of_interest, away, home),
      game_result = case_when(
        home == player_of_interest & game_winner == "home" ~ "W",
        away == player_of_interest & game_winner == "away" ~ "W",
        TRUE ~ "L"
      )
    ) %>% 
    inner_join(ratings_df %>% transmute(player, player_rating = rating), by = "player") %>% 
    inner_join(ratings_df %>% transmute(opponent = player, opponent_rating = rating), by = "opponent") %>% 
    mutate(
      A = 1 / (player_rating + opponent_rating),
      W = if_else(game_result == "W", 1, 0),
      decay = case_when(
        season == "Spring 2018" ~ 0.6,
        season == "Fall 2018" ~ 0.8,
        season == "Spring 2019" ~ 1.0
      )
    ) %>% 
    summarize(rating = ((a - 1) + sum(W * decay)) / (b + sum(A * decay))) %>% 
    pull(rating)
}
```

```{r}
results_to_ratings <- function(results_df, a, mae_stop = 100) {
  player_list <- 
    bind_rows(
      results_df %>% transmute(player = home), 
      results_df %>% transmute(player = away)
    ) %>% 
    distinct() %>% 
    arrange(player)
  
  fargo_ratings <- 
    player_list %>% 
    mutate(rating = 500)
  
  abs_diff <- 100000
  while (abs_diff > mae_stop) {
    old_ratings <- fargo_ratings %>% pull(rating)
    for (i in 1:nrow(fargo_ratings)) {
      player_name <- fargo_ratings$player[i]
      fargo_ratings$rating[i] <- 
        get_updated_rating(player_name, results_df = results_df, ratings_df = fargo_ratings, a = a)
    }
    new_ratings <- fargo_ratings %>% pull(rating)
    #print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
    abs_diff <- sum(abs(old_ratings - new_ratings))
  }
  
  fargo_ratings
}
```

```{r}
fargo_df <- 
  results_to_ratings(results_no_forfeits, a = 3, mae_stop = 100) %>% 
  mutate(
    rating = log(rating) * 144,
    rating = rating - mean(rating) + 500
  )
```

```{r}
fargo_df %>% 
  arrange(desc(rating))
```

```{r}
saveRDS(fargo_df, str_c("other_data/fargo_", latest_results_date, ".Rdata"))

```

```{r}
fargo_metrics <- function(results_df, a, date_idx) {
  player_list <- 
    bind_rows(
      results_df %>% transmute(player = home), 
      results_df %>% transmute(player = away)
    ) %>% 
    distinct() %>% 
    arrange(player)
  
  date_list <- 
    results_df %>% 
    select(match_date) %>% 
    distinct() %>% 
    pull()

  print(str_c("a = ", a, ", date = ", date_list[date_idx]))
  
  fargo_ratings <- 
    player_list %>% 
    mutate(rating = 500)
  
  training_data <- 
    results_df %>% 
    filter(match_date < date_list[date_idx])
  
  test_data <- 
    results_df %>% 
    filter(match_date == date_list[date_idx])
  
  abs_diff <- 100000
  while (abs_diff > 100) {
    old_ratings <- fargo_ratings %>% pull(rating)
    for (i in 1:nrow(fargo_ratings)) {
      player_name <- fargo_ratings$player[i]
      fargo_ratings$rating[i] <- 
        get_updated_rating(player_name, results_df = training_data, ratings_df = fargo_ratings, a = a)
    }
    new_ratings <- fargo_ratings %>% pull(rating)
    #print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
    abs_diff <- sum(abs(old_ratings - new_ratings))
  }
  
  matches_with_probabilities <- 
    test_data %>% 
    inner_join(fargo_ratings %>% transmute(home = player, home_rating = rating), by = "home") %>% 
    inner_join(fargo_ratings %>% transmute(away = player, away_rating = rating), by = "away") %>% 
    transmute(
      match_date,
      home,
      away, 
      game_winner,
      home_win_prob = home_rating / (home_rating + away_rating),
      home_win = if_else(game_winner == "home", 1, 0),
      home_win_predicted = if_else(home_win_prob >= 0.5, 1, 0),
      home_win_prob,
      prob = round(home_win_prob * 20) / 20
    )
  
  matches_with_probabilities %>% 
    mutate(
      correct_prediction = if_else(home_win == home_win_predicted, 1, 0),
      log_loss = home_win * log(home_win_prob) + (1 - home_win) * log(1 - home_win_prob),
      higher_ranked_prob = if_else(home_win_prob >= 0.5, home_win_prob, 1 - home_win_prob),
      higher_ranked_winner = case_when(
        home_win_prob >= 0.5 & home_win == 1 ~ 1,
        home_win_prob < 0.5 & home_win == 0 ~ 1,
        TRUE ~ 0
      )
    ) %>% 
    summarize(
      accuracy = mean(correct_prediction),
      log_loss = -mean(log_loss),
      calibration = sum(higher_ranked_prob) / sum(higher_ranked_winner),
      discrimination = 
        sum(higher_ranked_prob * higher_ranked_winner) / sum(higher_ranked_winner) - 
        sum(higher_ranked_prob * (1 - higher_ranked_winner)) / sum(1 - higher_ranked_winner)
    ) %>% 
    gather(key = metric, value = value, accuracy:discrimination) %>% 
    mutate(
      a = a,
      date_idx = date_list[date_idx]
    )
}
```

```{r}
test_df2 <- tibble()

for (i in 6:54) {
  for (a in seq(2.9, 3.3, by = 0.1)) {
    test_df2 <- bind_rows(
      test_df2,
      fargo_metrics(results_no_forfeits, a = a, date_idx = i)
    )
  }
}

test_df2
```

```{r}
test_df2 %>% 
  group_by(metric, a) %>% 
  summarize(value = mean(value)) %>% 
  filter(metric != "discrimination") %>% 
  ggplot(aes(x = a, y = value, group = metric, color = metric)) +
  geom_line() +
  geom_point()
```

```{r}
normalized_ratings <-
  fargo_ratings %>% 
  mutate(
    rating = log(rating) * 100,
    rating = rating - mean(rating) + 500
  )

normalized_ratings %>% 
  arrange(desc(rating2))
```

```{r}
fargo_ratings %>% 
  arrange(desc(rating)) %>% 
  mutate(rating2 = log(rating) * 100)
```

```{r}
4415 / (4415 + 3474)
```

```{r}
skip <- log(4415) * 100 - 100
thayer <- log(3474) * 100 - 100
```

```{r}
1 / (1 + exp((thayer - skip) / 100))
```

```{r}
fargo_ratings %>% 
  arrange(desc(rating))
```

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(lubridate)
library(pROC)

latest_fargo_date <- 
  list.files("other_data", pattern = "fargo") %>% 
  str_extract("\\d+-\\d+-\\d+") %>% 
  max()

fargo_path <-
  str_c("other_data/fargo_", latest_fargo_date, ".Rdata")

fargo_df <- 
  fargo_path %>% 
  read_rds()

latest_results_date <- 
  list.files("match_data", pattern = "results_no_forfeits") %>% 
  str_extract("\\d+-\\d+-\\d+") %>% 
  max()

results_no_forfeits_path <-
  str_c("match_data/results_no_forfeits_", latest_results_date, ".Rdata")

results_no_forfeits <- 
  results_no_forfeits_path %>% 
  read_rds()

results_19_no_forfeits <- 
  results_no_forfeits %>% 
  filter(season == "Spring 2019")

full_data <- 
  results_no_forfeits %>% 
  select(-c(forfeit:t2_end_rating))
```

```{r}
player_record <- function(player_of_interest, results_df) {
  results_df %>% 
  filter(away == player_of_interest | home == player_of_interest) %>% 
  mutate(
    player = player_of_interest,
    opponent = if_else(home == player_of_interest, away, home),
    game_result = case_when(
      home == player_of_interest & game_winner == "home" ~ "W",
      away == player_of_interest & game_winner == "away" ~ "W",
      TRUE ~ "L"
    )
  )
}

append_ratings_to_player_record <- function(player_record, current_ratings) {
  player_record %>% 
    inner_join(
      current_ratings %>% transmute(player, player_rating = rating), 
      by = "player"
    ) %>% 
    inner_join(
      current_ratings %>% transmute(opponent = player, opponent_rating = rating), 
      by = "opponent"
    )
}

generate_robustness <- function(results_df, games_to_full_robustness = 20) {
  robustness <- 
    bind_rows(results_df %>% select(player = home), results_df %>% select(player = away)) %>% 
    distinct() %>% 
    arrange(player) %>% 
    mutate(robustness = NA_integer_)
  
  for (i in 1:nrow(robustness)) {
    robustness$robustness[i] <- player_record(robustness$player[i], results_df) %>% count() %>% pull()
  }
  
  robustness %>% 
    transmute(
      player, 
      R = if_else(robustness > games_to_full_robustness, 1, robustness / games_to_full_robustness)
    )
}

generate_latest_match_date <- function(results_df) {
  latest_match_date <- 
    bind_rows(results_df %>% select(player = home), results_df %>% select(player = away)) %>% 
      distinct() %>% 
      arrange(player) %>% 
      mutate(latest_match_date = today())
  
  for (i in 1:nrow(latest_match_date)) {
      latest_match_date$latest_match_date[i] <- 
        player_record(latest_match_date$player[i], results_df) %>% pull(match_date) %>% max()
  }
  
  latest_match_date
}

updated_fargo_rating <- function(
  player_of_interest, gamma_prior = 1, results_df, current_ratings, half_life_days = 1500, robustness_df,
  latest_match_date_df
) {
  b <- ifelse(gamma_prior > 1, (gamma_prior - 1) / 500, 0)
  latest_match_date <- 
    latest_match_date_df %>% filter(player == player_of_interest) %>% pull(latest_match_date)
  
  player_record(player_of_interest = player_of_interest, results_df = results_df) %>% 
    append_ratings_to_player_record(current_ratings) %>% 
    left_join(robustness_df %>% transmute(opponent = player, R), by = "opponent") %>% 
    mutate(
      A = 1 / (player_rating + opponent_rating),
      W = if_else(game_result == "W", 1, 0),
      latest_match_date = latest_match_date,
      time_decay = 0.5 ^ (as.numeric(latest_match_date - match_date) / half_life_days)
    ) %>% 
    summarize(A = sum(A * time_decay * R), W = sum(W * time_decay * R)) %>% 
    mutate(rating = (gamma_prior - 1 + W) / (b + A)) %>% 
    pull(rating)
}

run_fargo_through_date <- function(
  as_of_match_date, 
  gamma_prior,
  half_life_days,
  games_to_robustness
) {
  print(str_c(
    "Matches through ", as_of_match_date, 
    ", gamma ", gamma_prior,
    ", half life ", half_life_days,
    ", robustness ", games_to_robustness
  ))
  
  df <-
    full_data %>% 
    filter(match_date <= as_of_match_date)
  
  robustness_df <- generate_robustness(df, games_to_robustness)
  latest_match_date_df <- generate_latest_match_date(df)
  
  current_fargo_ratings <- 
    bind_rows(df %>% select(player = home), df %>% select(player = away)) %>% 
    distinct() %>%
    arrange(player) %>% 
    mutate(rating = 500)
  
  mean_abs_diff <- 10000
  n_iter <- 0
  
  while (mean_abs_diff > 100) {
    n_iter <- n_iter + 1
    old_ratings <- current_fargo_ratings %>% pull(rating)
    for (i in 1:nrow(current_fargo_ratings)) {
      player_of_interest <- current_fargo_ratings$player[i]
      current_fargo_ratings$rating[i] <- updated_fargo_rating(
        player_of_interest = player_of_interest, 
        gamma_prior = gamma_prior, 
        results_df = df, 
        current_ratings = current_fargo_ratings,
        half_life_days = half_life_days,
        robustness_df = robustness_df,
        latest_match_date_df = latest_match_date_df
      )
    }
    new_ratings <- current_fargo_ratings %>% pull(rating)
    #print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
    mean_abs_diff <- sum(abs(old_ratings - new_ratings))
  }
  print(str_c("Converged in ", n_iter, " iterations"))
  
  current_fargo_ratings %>% 
    mutate(
      match_date = df %>% slice(n()) %>% pull(match_date),
      gamma_prior = gamma_prior,
      half_life_days = half_life_days,
      games_to_robustness = games_to_robustness
    )
}
```

```{r}
# RUN ALL DATES 
date_loop <- 
  full_data %>% 
  select(match_date) %>% 
  distinct() %>% 
  #slice(-c(1:6)) %>% 
  pull()

#param_list <- list(
#  as_of_match_date = rep(date_loop, 5), 
#  gamma_prior = rep(seq(2.5, 3.5, by = 0.25), each = length(date_loop)), 
#  half_life_days = 1500, 
#  games_to_robustness = 10
#)

param_list <- list(
  as_of_match_date = date_loop, 
  gamma_prior = 2.75, 
  half_life_days = 1500, 
  games_to_robustness = 15
)

fargo_df <- pmap_dfr(param_list, run_fargo_through_date)

fargo_df %>% 
  group_by(match_date) %>% 
  summarize(mean = mean(rating))

fargo_df %>%
  filter(match_date == fargo_df %>% select(match_date) %>% pull() %>% max()) %>% 
  arrange(desc(rating))

saveRDS(fargo_df, "other_data/fargo_327.Rdata")



# OR JUST RUN ONE DAY AND APPEND TO OLD VERSION

old_data <-
  fargo_df

param_list <- list(
  as_of_match_date = latest_results_date, 
  gamma_prior = 2.75, 
  half_life_days = 1500, 
  games_to_robustness = 15
)

new_data <- pmap_dfr(param_list, run_fargo_through_date)

old_data %>% 
  group_by(match_date) %>% 
  summarize(mean = mean(rating))

new_data %>% 
  summarize(mean = mean(rating))

fargo_df <-
  bind_rows(old_data, new_data)

saveRDS(fargo_df, str_c("other_data/fargo_", latest_results_date, ".Rdata"))
```

```{r}

```

```{r}
gam_loop <- fargo_df %>% select(gamma_prior) %>% distinct() %>% pull()

auc_results <- rep(0, length(gam_loop))
log_loss_results <- rep(0, length(gam_loop))
accuracy_results <- rep(0, length(gam_loop))

win_prob_summary <- tribble(
  ~wins, ~nsize, ~win_pct, ~gamma_prior
)

for (i in 1:length(gam_loop)) {
  gam <- gam_loop[i]
  
  lagged_ratings <- 
    fargo_df %>% 
    ungroup() %>% 
    filter(gamma_prior == gam) %>% 
    group_by(player) %>% 
    mutate(rating = replace_na(lag(rating, n = 1), 500)) %>% 
    arrange(player, match_date) %>% 
    ungroup()
  
  test_set_with_win_probs <- 
    full_data %>% 
    filter(match_date > "2018-03-01") %>% 
    #filter(season == "Spring 2019", match_date > "2019-02-05") %>% 
    left_join(lagged_ratings %>% transmute(match_date, home = player, home_rating = rating), by = c("match_date", "home")) %>% 
    left_join(lagged_ratings %>% transmute(match_date, away = player, away_rating = rating), by = c("match_date", "away"))  %>% 
    mutate(
      home_win = if_else(game_winner == "home", 1, 0),
      home_win_prob = home_rating / (home_rating + away_rating),
      prob = round(home_win_prob, 1)
    )
  
  match_results <- test_set_with_win_probs %>% pull(home_win)
  match_probabilities <- test_set_with_win_probs %>% pull(home_win_prob)

  win_prob_summary <- bind_rows(
    win_prob_summary,
    test_set_with_win_probs %>% 
      group_by(prob) %>% 
      summarize(
        wins = sum(home_win),
        nsize = n(),
        win_pct = wins / nsize
      ) %>% 
      ungroup() %>% 
      mutate(
        auc = as.numeric(auc(roc(match_results, match_probabilities))),
        log_loss = -1 / length(match_results) * sum(
          match_results * log(match_probabilities) + 
            (1 - match_results) * log(1 - match_probabilities)
          ),
        accuracy = sum(match_results == round(match_probabilities)) / length(match_results),
        gamma_prior = gam
      )
  )
}

win_prob_summary
```

```{r}
win_prob_summary %>% 
  filter(gamma_prior < 3.25) %>% 
  mutate(gam = as.factor(gamma_prior)) %>% 
  ggplot(aes(x = prob, y = win_pct, group = gam, color = gam)) +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_line() +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(
    title = "Predicted Probability vs. Win Percentage"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
win_prob_summary %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(gamma_prior) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = gamma_prior, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  labs(
    title = "Weighted MAE Across Gamma Priors"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
win_prob_summary %>% 
  distinct(auc, log_loss, accuracy, gamma_prior) %>% 
  gather(metric, value, -gamma_prior) %>% 
  ggplot(aes(x = gamma_prior, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Performance Metrics Comparison"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
df_test_3 %>% 
  group_by(match_date) %>% 
  summarize(mean = mean(rating))

saveRDS(df_test_3, "other_data/fargo_3_seasons_initial.Rdata")
```

```{r}
fargo_df <- readRDS("other_data/fargo_324.Rdata")

team_members <- function(team_name) {
  bind_rows(
    full_data %>% filter(season == "Spring 2019", home_team == team_name) %>% select(player = home),
    full_data %>% filter(season == "Spring 2019", away_team == team_name) %>% select(player = away)
  ) %>% 
    distinct(player) %>% 
    arrange(player) %>% 
    pull()
}

plot_multiple_player_ratings <- function(player_list, df) {
  df %>% 
    filter(player %in% player_list) %>% 
    ggplot(aes(x = match_date, y = rating, color = player, group = player)) +
    geom_hline(yintercept = 500, size = 2, color = "white") +
    geom_point(size = 1) +
    geom_line() +
    labs(
      x = "Match Date", y = "Rating"
    ) +
    coord_cartesian(ylim = c(0, 2000)) +
    theme(
      legend.title = element_blank(),
      plot.title = element_text(hjust = 0.5),
      legend.position = "bottom",
      legend.text = element_text(size = 9.5)
    )
}

plot_multiple_player_ratings(player_list = team_members("Tandy Tokers"), fargo_df)
plot_multiple_player_ratings(player_list = team_members("Route 101 Rawhides"), fargo_df)
plot_multiple_player_ratings(player_list = team_members("Cafe Strikes Again"), fargo_df)
plot_multiple_player_ratings(player_list = team_members("Lucky Horseshoe Caballeros"), fargo_df)
plot_multiple_player_ratings(player_list = team_members("Harry's Humdingers"), fargo_df)
plot_multiple_player_ratings(player_list = c("Jesse La Fear", "Nick Callado"), fargo_df)
```

```{r}
player_record("Jesse La Fear", full_data)
```


```{r}
# Look at robustness level 

fargo_df <- 
  readRDS("other_data/fargo_324.Rdata") %>% 
  transmute(player, rating, match_date)

#sizes <- 
#  fargo_df %>% 
#  arrange(player, match_date) %>% 
#  group_by(player) %>% 
#  mutate(
#    game = row_number(),
#    diff = rating - lag(rating)
#  ) %>% 
#  group_by(game) %>% 
#  count()

fargo_df %>% 
  arrange(player, match_date) %>% 
  group_by(player) %>% 
  mutate(
    game = row_number(),
    diff = rating - lag(rating)
  ) %>% 
  ungroup() %>% 
  group_by(game) %>% 
  summarize(
    mean = mean(diff),
    median = median(diff),
    sdev = sd(diff)
  ) %>% 
#  left_join(sizes, by = "game") %>% 
  filter(!is.na(mean)) %>% 
  gather(metric, value, mean:sdev) %>% 
  ggplot(aes(x = game, y = value, color = metric, group = metric)) +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line()
  
```




```{r}
df_test_2 %>% 
  filter(rating < 1500) %>% 
  ggplot(aes(x = match_date, y = rating, group = player)) +
  geom_line(alpha = 0.2)
```

```{r}
sdevs <- 
  df_test_3 %>% 
  group_by(player) %>% 
  summarize(sdev = sd(rating))

df_test_3 %>% 
  left_join(sdevs, by = "player") %>% 
  filter(sdev > 120) %>% 
  ggplot(aes(x = match_date, y = rating, group = player, color = player)) +
  geom_line() +
  geom_point(size = 1)
```

```{r}
top_10_players <- 
  df_test_3 %>% 
  filter(match_date > "2018-05-01") %>% 
  arrange(desc(rating)) %>% 
  group_by(match_date) %>% 
  mutate(rank = row_number()) %>% 
  ungroup() %>% 
  filter(rank < 5) %>% 
  select(player) %>% 
  distinct()

df_test_3 %>% 
  filter(match_date > "2018-05-01") %>% 
  arrange(desc(rating)) %>% 
  group_by(match_date) %>% 
  mutate(rank = row_number()) %>% 
  ungroup() %>% 
  inner_join(top_10_players, by = "player") %>% 
  ggplot(aes(x = match_date, y = rank, group = player, color = player)) +
  geom_line() +
  geom_point(size = 1) +
  coord_cartesian(ylim = c(0, 25))
```

```{r}
lagged_ratings <- 
  df_test_3 %>% 
  group_by(player) %>% 
  mutate(rating = replace_na(lag(rating, n = 1), 500)) %>% 
  arrange(player, match_date) %>% 
  ungroup()

lagged_ratings %>% 
  filter(player == "Jerry Ervin")
```




```{r}
# Needs from out of function:
# cv_folds number
# full_data, robustness, latest_match_date data frames
cv_prior_testing <- function(gamma_prior) {
  auc_results <- rep(0, cv_folds)
  log_loss_results <- rep(0, cv_folds)
  accuracy_results <- rep(0, cv_folds)
  
  probs_vs_wins <- 
    tribble(
      ~prob, ~wins, ~nsize
    )
  
  decay_factor <- 1500
  
  robustness_df <- generate_robustness(full_data)
  latest_match_date_df <- generate_latest_match_date(full_data)

  print(str_c("Testing gamma prior ", gamma_prior))
  
  for (c in 1:cv_folds) {
    print(str_c("CV fold ", c))
    train_data <- full_data %>% filter(cv != c)
    test_data <- full_data %>% filter(cv == c)
    
    current_fargo_ratings <- 
      bind_rows(train_data %>% select(player = home), train_data %>% select(player = away)) %>% 
      distinct() %>%
      arrange(player) %>% 
      mutate(rating = 500)
    
    mean_abs_diff <- 10000
    n_iter <- 0
    
    while (mean_abs_diff > 100) {
      n_iter <- n_iter + 1
      old_ratings <- current_fargo_ratings %>% pull(rating)
      for (i in 1:nrow(current_fargo_ratings)) {
        player_of_interest <- current_fargo_ratings$player[i]
        current_fargo_ratings$rating[i] <- updated_fargo_rating(
          player_of_interest = player_of_interest, 
          gamma_prior = gamma_prior, 
          results_df = train_data, 
          current_ratings = current_fargo_ratings,
          decay_factor = decay_factor,
          robustness_df = robustness_df,
          latest_match_date_df = latest_match_date_df
        )
      }
      new_ratings <- current_fargo_ratings %>% pull(rating)
      print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
      mean_abs_diff <- sum(abs(old_ratings - new_ratings))
    }
    print(str_c("Converged in ", n_iter, " iterations"))
    
    test_set_with_win_probs <-
      test_data %>% 
        transmute(player = home, opponent = away, game_winner) %>% 
        append_ratings_to_player_record(current_fargo_ratings)  %>% 
        mutate(
          player_win = if_else(game_winner == "home", 1, 0),
          player_win_prob = player_rating / (player_rating + opponent_rating),
          prob = round(player_win_prob, 1)
        )
    
    match_results <- test_set_with_win_probs %>% pull(player_win)
    match_probabilities <- test_set_with_win_probs %>% pull(player_win_prob)
    
    auc_results[c] <- as.numeric(auc(roc(match_results, match_probabilities)))
    
    log_loss_results[c] <- 
      -1 / length(match_results) * sum(
        match_results * log(match_probabilities) + 
          (1 - match_results) * log(1 - match_probabilities)
      )
    
    accuracy_results[c] <- sum(match_results == round(match_probabilities)) / length(match_results)
    
    probs_vs_wins_cv <- 
      test_set_with_win_probs %>% 
        group_by(prob) %>% 
        summarize(
          wins = sum(player_win),
          nsize = n()
        )
    
    probs_vs_wins <- 
      bind_rows(
        probs_vs_wins,
        probs_vs_wins_cv
      )
  }
  
  probs_vs_wins %>% 
    group_by(prob) %>% 
    summarize(
      wins = sum(wins),
      nsize = sum(nsize)
    ) %>% 
    mutate(
      win_pct = wins / nsize,
      auc = mean(auc_results),
      log_loss = mean(log_loss_results),
      accuracy = mean(accuracy_results),
      gamma_prior = gamma_prior
    )
}
```

```{r}


cv_testing_4 <- map_dfr(c(1.1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5), cv_prior_testing)

map_dfr(2.5, cv_prior_testing)
```

```{r}
#cv_testing_3 <- 
#  map_dfr(c(4, 5), cv_prior_testing)

# saveRDS(cv_testing_3, "other_data/cv_testing_320.Rdata")
saveRDS(cv_testing_4, "other_data/cv_testing_321.Rdata")
```

```{r}
cv_testing_3 <- readRDS("other_data/cv_testing_320.Rdata")

cv_testing_4 %>% 
  #filter(gamma_prior > 2.5, gamma_prior < 5.5) %>% 
  mutate(gamma_prior = as.factor(gamma_prior)) %>% 
  ggplot(aes(x = prob, y = win_pct, color = gamma_prior, group = gamma_prior)) +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(
    title = "Predicted Probability vs. Win Percentage"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
cv_testing_4 %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(gamma_prior) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = gamma_prior, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  labs(
    title = "Weighted MAE Across Gamma Priors"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
cv_testing_4 %>% 
  distinct(auc, log_loss, accuracy, gamma_prior) %>% 
  gather(metric, value, -gamma_prior) %>% 
  ggplot(aes(x = gamma_prior, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Performance Metrics Comparison"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
# NEED TO UPDATE

# Select best gamma prior and run ratings on full data set
gamma_prior <- 2.5

final_fargo_ratings <- 
  bind_rows(full_data %>% select(player = home), full_data %>% select(player = away)) %>% 
  distinct() %>%
  arrange(player) %>% 
  mutate(rating = 500)

mean_abs_diff <- 10000
decay_factor <- 1500
n_iter <- 0

while (mean_abs_diff > 50) {
  n_iter <- n_iter + 1
  old_ratings <- final_fargo_ratings %>% pull(rating)
  for (i in 1:nrow(final_fargo_ratings)) {
    player_of_interest <- final_fargo_ratings$player[i]
    final_fargo_ratings$rating[i] <- updated_fargo_rating(
      player_of_interest = player_of_interest, 
      gamma_prior = gamma_prior, 
      results_df = full_data, 
      current_ratings = final_fargo_ratings,
      decay_factor = decay_factor,
      robustness_df = robustness
    )
  }
  new_ratings <- final_fargo_ratings %>% pull(rating)
  print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
  mean_abs_diff <- sum(abs(old_ratings - new_ratings))
}
print(str_c("Converged in ", n_iter, " iterations"))

final_fargo_ratings %>% 
  arrange(desc(rating))

saveRDS(final_fargo_ratings, "other_data/fargo_ratings_321.Rdata")
```


```{r}
results_no_forfeits %>% 
  filter(away == "Jonathan")
```

