---
title: "SFPA Ratings Scratch"
author: "Skip Perry"
date: "3/16/2019"
output: html_document
---


```{r}
# Home vs. away performance - this doesn't show much of interest
team_list <- 
  bind_rows(
    results_19_no_forfeits %>% select(home_team) %>% transmute(team = home_team),
    results_19_no_forfeits %>% select(away_team) %>% transmute(team = away_team)
  ) %>% 
  distinct() %>% 
  arrange(team) %>% 
  pull()

home_away_win_pct <- function(team_name) {
  results_no_forfeits %>% 
    filter(week_number > 1, week_number < 50) %>% 
    mutate(
      location = if_else(
        home_team == team_name, "home",
        if_else(
          away_team == team_name, "away", NA_character_
        )
      )
    ) %>% 
    filter(!is.na(location)) %>% 
    mutate(
      result = if_else(
        (location == "home" & game_winner == "home") | (location == "away" & game_winner == "away"), 
        1, 
        0
      )
    ) %>% 
    group_by(location) %>% 
    summarize(
      total_games = n(),
      win_pct = mean(result)
    ) %>% 
    mutate(total_games = sum(total_games)) %>% 
    spread(location, win_pct) %>% 
    mutate(home_adv = home - away) %>% 
    gather(key = "location", value = "win_pct", home, away, -home_adv, -total_games) %>% 
    mutate(
      team_name = team_name,
      overall_win_pct = mean(win_pct)
    )
}
  
map_dfr(team_list, home_away_win_pct) %>% 
  ggplot(aes(x = reorder(team_name, win_pct), y = win_pct, color = location)) +
  geom_point() +
  coord_flip() +
  theme(axis.title = element_blank())

map_dfr(team_list, home_away_win_pct) %>% 
  distinct(home_adv, team_name) %>% 
  group_by(home_adv > 0) %>% 
  count()
```

```{r}
# Summarize players' win-loss records against all relevant opponents
# This appears not to be used for anything right now

# Turn full player list into a vector instead of a data frame
player_list_vector <- 
  full_player_list(results_no_forfeits) %>% 
  pull(player)

# Construct data frame summary of a given player, their opponents, wins, and losses
player_win_loss_summary <- function(player_of_interest) {
  df <-
    player_matches_and_ratings(player_of_interest) %>% 
    slice(-1) %>%                        # Removes the blank line for 1500 starter rating
    count(player, opponent, result) %>% 
    spread(result, n)
  
  df <- 
    if (("W") %in% names(df)) { 
      df 
    } else {
      df %>% mutate(W = 0)
    }

  df <- 
    if (("L") %in% names(df)) { 
      df 
    } else {
      df %>% mutate(L = 0)
    }
  
  df %>% 
    transmute(
      player, opponent,
      W = replace_na(W, 0),
      L = replace_na(L, 0),
      total_games = W + L
    ) %>% 
    arrange(-total_games, -W)
}

full_win_loss_summary <- 
  map_dfr(player_list_vector, player_win_loss_summary)

#full_win_loss_summary
```


```{r}
library(shiny)

ui <- fluidPage(
  h1("My app"),
  mainPanel(
    plotOutput(
      "plot1",
      click = "plot_click",
      dblclick = "plot_dblclick",
      hover = "plot_hover",
      brush = "plot_brush"
    )
  ),
  verbatimTextOutput("info")
)

server <- function(input, output) {
  output$plot1 <- renderPlot({
    map_dfr(get_team_players("Tandy Tokers"), player_rating_progress) %>% 
      group_by(match_date, player) %>% 
      slice(n()) %>% 
      ggplot(aes(x = match_date, y = new_rating, group = player, color = player)) +
      geom_hline(yintercept = 1500, color = "gray50") +
      geom_line() +
      geom_point()
  })
  
  output$info <- renderText({
    xy_str <- function(e) {
      if(is.null(e)) return("NULL\n")
      paste0("x=", round(e$x, 1), " y=", round(e$y, 1), "\n")
    }
    xy_range_str <- function(e) {
      if(is.null(e)) return("NULL\n")
      paste0("xmin=", round(e$xmin, 1), " xmax=", round(e$xmax, 1), 
             " ymin=", round(e$ymin, 1), " ymax=", round(e$ymax, 1))
    }

    paste0(
      "click: ", xy_str(input$plot_click),
      "dblclick: ", xy_str(input$plot_dblclick),
      "hover: ", xy_str(input$plot_hover),
      "brush: ", xy_range_str(input$plot_brush)
    )
  })

}

shinyApp(ui, server)
```


```{r}
distinct_players <- 
  bind_rows(
    home_players, 
    away_players
  ) %>% 
  distinct(player) %>% 
  pull()

df <-
  results_no_forfeits %>% 
  count(home, away, game_winner) %>% 
  mutate(game_winner = if_else(game_winner == "home", "home_win", "away_win")) %>% 
  spread(key = game_winner, value = n) %>% 
  mutate(
    home_win = replace_na(away_win, 0),
    away_win = replace_na(away_win, 0),
    home = factor(home, levels = unique(c(home, away))),
    away = factor(away, levels = levels(home))
  )

install.packages("Matrix.utils")
library(Matrix.utils)
library(BradleyTerryScalable)

btdata <- btdata(df)
btdata_fit <- btfit(btdata, 1)
summary(btdata_fit)
coef(btdata_fit)
summary.btfit(btdata_fit)


df$away %>% fct_relevel(distinct_players)
df$home %>% fct_relevel(distinct_players)


levels(df$home)

countsToBinomial(df)
library(BradleyTerry2)
citeModel <- BTm(cbind(home_win, away_win), home, away, data = df)
citeModel
3;
```







```{r}
A_rating <- 1650
B_rating <- 1550
C_rating <- 1550
D_rating <- 1450

set.seed(10)

df <- 
  tribble(
    ~home, ~away, ~game_winner,
    "A", "B", "home",
    "A", "C", "away",
    "A", "D", "home",
    "B", "C", "home",
    "B", "D", "home",
    "C", "D", "away",
    "A", "B", "home",
    "A", "C", "home",
    "A", "D", "home",
    "B", "C", "away",
    "B", "D", "home",
    "C", "D", "home"
  )

fargo_ratings <-
  tibble(
    player = c("A", "B", "C", "D"),
    rating = rep(1500, 4)
  )

df %>% 
  filter(str_detect(home, "A"))

f <- function(A) (A / (A + B_rating))

f(1650)

```








```{r}
url <- 'https://www.sfpapool.org/stats/player/3945/'

webpage <- read_html(url)

player_name <- 
  webpage %>% 
  html_nodes("h3") %>% 
  html_text() %>% 
  str_extract("\\w+\\s\\w+")

player_team_name <- 
  webpage %>% 
  html_nodes("tbody") %>% 
  html_nodes("tr") %>% 
  html_text() %>% 
  as_tibble() %>% 
  filter(str_detect(value, "Spring 2019")) %>% 
  mutate(value = str_extract(value, pattern = "(.)+\n\\s+\\w+\\s\\w+")) %>% 
  mutate(value = str_remove(value, pattern = "(.)+\n\\s+")) %>% 
  as.character()

webpage %>% 
  html_nodes("tbody") %>% 
  html_nodes("tr") %>% 
  html_text() %>% 
  
webpage %>% 
  html_nodes("div") %>% 
  html_text() %>% 
  as_tibble() %>% 
  filter(str_detect(value, "^\\w")) %>% 
  separate(value, into = c("information", "matches"), sep = "TR") %>% 
  mutate(
    date = str_extract(information, pattern = "^\\w+\\.\\s\\d+\\,\\s\\d+"),
    week = str_extract(information, pattern = "Week\\s\\d+"),
    week = as.numeric(str_extract(information, pattern = "\\d+"))
  ) %>% 
  separate(matches, into = c("match1", "match2", "match3", "match4"), sep = "\n\\s+\n") %>% 
  mutate(match1 = str_remove(match1, pattern = "^\n\\s")) %>% 
  separate(match1, into = c("gm1_op", "gm1_result"), sep = "\n") %>% 
  separate(match2, into = c("gm2_op", "gm2_result"), sep = "\n") %>% 
  separate(match3, into = c("gm3_op", "gm3_result"), sep = "\n") %>% 
  separate(match4, into = c("gm4_op", "gm4_result"), sep = "\n")

webpage %>% 
  html_nodes("tr") %>% 
  html_text() %>% 
  as_tibble() %>% 
  filter(!str_detect(value, "@|Opponent")) %>% 
  mutate(value = str_extract(value, "(.)+\n\\s+\\w")) %>% 
  mutate(player1 = player_name) %>% 
  separate(value, into = c("player2", "result"), sep = "\n")

webpage %>% 
  html_nodes("div") %>% 
  html_nodes("div") %>% 
  html_nodes("div") %>% 
  html_text() %>% 
  as_tibble() %>% 
  filter(str_detect(value, "\\w+\\s\\w+|--")) %>% 
  filter(!str_detect(value, "^\n"))
```

```{r}
#elo_ratings
get_win_loss_record <- function(player_of_interest) {
  df <- 
    results_19_no_forfeits %>% 
    filter(home == player_of_interest | away == player_of_interest) %>% 
    mutate(
      player = player_of_interest,
      game_result = case_when(
        away == player_of_interest & game_winner == "away" ~ "W",
        home == player_of_interest & game_winner == "home" ~ "W",
        TRUE ~ "L"
      )
    ) %>% 
    count(player, game_result) %>% 
    spread(game_result, n)
  
  df <- 
    if (("W") %in% names(df)) { 
      df 
    } else {
      df %>% mutate(W = 0)
    }

  df <- 
    if (("L") %in% names(df)) { 
      df 
    } else {
      df %>% mutate(L = 0)
    }

  df %>% 
    select(player, W, L) %>% 
    mutate(pct = W / L) %>% 
    left_join(elo_ratings, by = "player")
}
get_win_loss_record(player_of_interest = "Buddy Jacques")


```