---
title: "SFPA Individual ELO Ratings K Optimization"
author: "Skip Perry"
date: "3/14/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(lubridate)
library(pROC)
source("02_data_clean.R")

cv_folds <- 4

set.seed(13)
full_data <- 
  results_no_forfeits %>% 
  select(-c(forfeit:t2_end_rating)) %>% 
  mutate(cv = sample.int(cv_folds, nrow(.), replace = TRUE)) %>% 
  mutate(
    p1_initial = NA_real_,
    p1_postgame = NA_real_,
    p2_initial = NA_real_,
    p2_postgame = NA_real_,
    t1_initial = NA_real_,
    t1_postgame = NA_real_,
    t2_initial = NA_real_,
    t2_postgame = NA_real_
  )
```

```{r}
K_testing <- function(K_player, K_team) {
  
  print(str_c("K_player: ", K_player))
  print(str_c("K_team: ", K_team))
  
  auc_player_results <- rep(0, cv_folds)
  log_loss_player_results <- rep(0, cv_folds)
  accuracy_player_results <- rep(0, cv_folds)
  auc_team_results <- rep(0, cv_folds)
  log_loss_team_results <- rep(0, cv_folds)
  accuracy_team_results <- rep(0, cv_folds)
  
  probs_vs_wins <- 
    tribble(
      ~prob, ~wins, ~nsize, ~category, ~cv
    )
  
  for (c in 1:cv_folds) {
    print(str_c("* CV fold ", c))
    train_data <- full_data %>% filter(cv != c)
    test_data <- full_data %>% filter(cv == c)
    
    current_elo_player_ratings <- 
      bind_rows(train_data %>% select(player = home), train_data %>% select(player = away)) %>% 
      distinct() %>%
      arrange(player) %>% 
      mutate(rating = 1500)
    
    current_elo_team_ratings <- 
      bind_rows(train_data %>% select(team = home_team), train_data %>% select(team = away_team)) %>% 
      distinct() %>%
      arrange(team) %>% 
      mutate(rating = 1500)
    
    for (i in 1:nrow(train_data)) {
      home_player <- train_data$home[i]
      away_player <- train_data$away[i]
      home_team <- train_data$home_team[i]
      away_team <- train_data$away_team[i]
      home_player_rating <- 
        current_elo_player_ratings$rating[current_elo_player_ratings$player == home_player]
      away_player_rating <- 
        current_elo_player_ratings$rating[current_elo_player_ratings$player == away_player]
      home_team_rating <- 
        current_elo_team_ratings$rating[current_elo_team_ratings$team == home_team]
      away_team_rating <- 
        current_elo_team_ratings$rating[current_elo_team_ratings$team == away_team]
      train_data$p1_initial[i] <- home_player_rating
      train_data$p2_initial[i] <- away_player_rating
      train_data$t1_initial[i] <- home_team_rating
      train_data$t2_initial[i] <- away_team_rating
      home_player_win_prob <- 1 / (1 + 10 ^ ((away_player_rating - home_player_rating) / 400))
      away_player_win_prob <- 1 - home_player_win_prob
      home_team_win_prob <- 1 / (1 + 10 ^ ((away_team_rating - home_team_rating) / 400))
      away_team_win_prob <- 1 - home_team_win_prob
      S1 <- ifelse(train_data$game_winner[i] == "home", 1, 0)
      S2 <- 1 - S1
      home_player_rating_new <- home_player_rating + K_player * (S1 - home_player_win_prob)
      away_player_rating_new <- away_player_rating + K_player * (S2 - away_player_win_prob)
      home_team_rating_new <- home_team_rating + K_team * (S1 - home_team_win_prob)
      away_team_rating_new <- away_team_rating + K_team * (S2 - away_team_win_prob)
      current_elo_player_ratings$rating[current_elo_player_ratings$player == home_player] <- home_player_rating_new
      current_elo_player_ratings$rating[current_elo_player_ratings$player == away_player] <- away_player_rating_new
      current_elo_team_ratings$rating[current_elo_team_ratings$team == home_team] <- home_team_rating_new
      current_elo_team_ratings$rating[current_elo_team_ratings$team == away_team] <- away_team_rating_new
      train_data$p1_postgame[i] <- home_player_rating_new
      train_data$p2_postgame[i] <- away_player_rating_new
      train_data$t1_postgame[i] <- home_team_rating_new
      train_data$t2_postgame[i] <- away_team_rating_new
    }
    
    test_set_with_win_probs <-
      test_data %>% 
      inner_join(
        current_elo_player_ratings %>% transmute(home = player, home_player_rating = rating),
        by = "home"
      ) %>% 
      inner_join(
        current_elo_player_ratings %>% transmute(away = player, away_player_rating = rating),
        by = "away"
      ) %>% 
      inner_join(
        current_elo_team_ratings %>% transmute(home_team = team, home_team_rating = rating),
        by = "home_team"
      ) %>% 
      inner_join(
        current_elo_team_ratings %>% transmute(away_team = team, away_team_rating = rating),
        by = "away_team"
      ) %>% 
      mutate(
        home_player_win_prob = 1 / (1 + 10 ^ ((away_player_rating - home_player_rating) / 400)),
        home_team_win_prob = 1 / (1 + 10 ^ ((away_team_rating - home_team_rating) / 400)),
        home_win = if_else(game_winner == "home", 1, 0),
        home_player_win_prob_round = round(home_player_win_prob, 1),
        home_team_win_prob_round = round(home_team_win_prob, 1)
      )
    
    match_results <- test_set_with_win_probs %>% pull(home_win)
    player_probabilities <- test_set_with_win_probs %>% pull(home_player_win_prob)
    team_probabilities <- test_set_with_win_probs %>% pull(home_team_win_prob)
    
    auc_player_results[c] <- as.numeric(auc(roc(match_results, player_probabilities)))
    
    log_loss_player_results[c] <- 
      -1 / length(match_results) * sum(
        match_results * log(player_probabilities) + 
          (1 - match_results) * log(1 - player_probabilities)
      )
    
    accuracy_player_results[c] <- sum(match_results == round(player_probabilities)) / length(match_results)
    
    auc_team_results[c] <- as.numeric(auc(roc(match_results, team_probabilities)))
    
    log_loss_team_results[c] <- 
      -1 / length(match_results) * sum(
        match_results * log(team_probabilities) + 
          (1 - match_results) * log(1 - team_probabilities)
      )
    
    accuracy_team_results[c] <- sum(match_results == round(team_probabilities)) / length(match_results)
    
    probs_vs_wins_player_cv <- 
      test_set_with_win_probs %>% 
      group_by(prob = home_player_win_prob_round) %>% 
      summarize(
        wins = sum(home_win),
        nsize = n()
      ) %>% 
      mutate(
        category = "player",
        cv = c
      )
    
    probs_vs_wins_team_cv <- 
      test_set_with_win_probs %>% 
      group_by(prob = home_team_win_prob_round) %>% 
      summarize(
        wins = sum(home_win),
        nsize = n()
      ) %>% 
      mutate(
        category = "team",
        cv = c
      )
    
    probs_vs_wins <- 
      bind_rows(
        probs_vs_wins,
        probs_vs_wins_player_cv,
        probs_vs_wins_team_cv
      )
  }
  
  cv_collapsed <- 
    probs_vs_wins %>% 
    group_by(prob, category) %>% 
    summarize(
      wins = sum(wins),
      nsize = sum(nsize)
    ) %>% 
    mutate(win_pct = wins / nsize)
  
  metrics <- 
    tribble(
      ~auc, ~log_loss, ~accuracy, ~category,
      mean(auc_player_results), mean(log_loss_player_results), mean(accuracy_player_results), "player",
      mean(auc_team_results), mean(log_loss_team_results), mean(accuracy_team_results), "team"
    )
  
  cv_collapsed %>% 
    left_join(metrics, by = "category") %>% 
    arrange(category, prob) %>% 
    mutate(
      K_player = K_player, 
      K_team = K_team
    ) %>% 
    ungroup()
}
```

```{r}
df_test <-
  K_testing(K_player = 20, K_team = 5)

df_test

df_test <- map2_dfr(c(15:35), 5, K_testing)
```


```{r}
df_test %>% 
  filter(category == "player") %>% 
  mutate(K_player = as.factor(K_player)) %>% 
  ggplot(aes(x = prob, y = win_pct, color = K_player, group = K_player)) +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(
    title = "Predicted Probability vs. Win Percentage"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
df_test %>% 
  filter(category == "player") %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(K_player) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = K_player, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  labs(
    title = "Weighted MAE Across K"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )

```

```{r}
df_test %>% 
  filter(category == "player") %>% 
  select(log_loss, accuracy, K_player) %>% 
  distinct() %>% 
  gather(metric, value, -K_player) %>% 
  ggplot(aes(x = K_player, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Performance Metrics Comparison"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
current_elo_player_ratings %>% 
  arrange(desc(rating))

current_elo_team_ratings %>% 
  arrange(desc(rating))
```

```{r}
# Data frame of players and team names in Spring 2019 - helper for next helper function
players_by_team_19 <- 
  bind_rows(
    results_19_no_forfeits %>% distinct(home_team, home) %>% transmute(player = home, team = home_team),
    results_19_no_forfeits %>% distinct(away_team, away) %>% transmute(player = away, team = away_team)
  ) %>% 
    distinct() %>% 
    arrange(team, player)

# Helper function to add team names to a data frame containing a column for player
append_team_names <- function(df) {
  df %>% 
    full_join(players_by_team_19, by = "player")
}

# Helper function to get a player's rating
get_rating <- function(player_name, ratings_df) {
  ratings_df %>% 
    filter(player == player_name) %>% 
    pull(rating)
}

# Helper function to get player list
full_player_list <- function(df) {
  bind_rows(
    df %>% select(home) %>% transmute(player = home), 
    df %>% select(away) %>% transmute(player = away)
  ) %>% 
    distinct(player) %>% 
    arrange(player)
}

# Helper function for ELO match win probability
match_win_probability <- function(player_of_interest, home_rating, away_rating, home_advantage) {
  if (player_of_interest == "home") {
    prob <- 1 / (1 + 10 ^ ((away_rating - (home_rating + home_advantage)) / 400))
  } else {
    prob <- 1 / (1 + 10 ^ (((home_rating + home_advantage) - away_rating) / 400))
  }
  prob
}
```

```{r}
# Function for simulating results at different levels of K
k_testing <- function(K) {
  print(str_c("Starting k = ", K))
  
  elo_ratings <-
    full_player_list(train) %>% 
    mutate(rating = 1500)
  
  train_internal <- train
  
  for (i in 1:nrow(train_internal)) {
    player1 <- train_internal$home[i]
    player2 <- train_internal$away[i]
    player1_rating <- get_rating(player1, elo_ratings)
    player2_rating <- get_rating(player2, elo_ratings)
    train_internal$p1_start_rating[i] <- player1_rating
    train_internal$p2_start_rating[i] <- player2_rating
    player1_expected <-
      match_win_probability(
        player_of_interest = "home", home_rating = player1_rating, away_rating = player2_rating,
        home_advantage = home_advantage
      )
    player2_expected <-
      match_win_probability(
        player_of_interest = "away", home_rating = player1_rating, away_rating = player2_rating,
        home_advantage = home_advantage
      )
    winner <- train_internal$game_winner[i]
    S1 <- ifelse(winner == "home", 1, 0)
    S2 <- ifelse(winner == "home", 0, 1)
    player1_rating_new = player1_rating + K * (S1 - player1_expected)
    player2_rating_new = player2_rating + K * (S2 - player2_expected)
    elo_ratings$rating[elo_ratings$player == player1] <- player1_rating_new
    elo_ratings$rating[elo_ratings$player == player2] <- player2_rating_new
    train_internal$p1_end_rating[i] <- player1_rating_new
    train_internal$p2_end_rating[i] <- player2_rating_new
  }
    
  df <- 
    test %>% 
    select(home_player = home, away_player = away, game_winner) %>% 
    inner_join(
      elo_ratings %>% transmute(home_player = player, home_rating = rating),
      by = "home_player"
    ) %>% 
    inner_join(
      elo_ratings %>% transmute(away_player = player, away_rating = rating),
      by = "away_player"
    ) %>% 
    mutate(
      home_win = if_else(game_winner == "home", 1, 0),
      home_win_prob = 1 / (1 + 10 ^ ((away_rating - (home_rating + home_advantage)) / 400)),
      prob = round(home_win_prob, 1)
    ) %>% 
    arrange(home_win_prob)
  
  auc_result <- as.numeric(auc(roc(df %>% pull(home_win), df %>% pull(home_win_prob))))

  print(str_c("AUC = ", auc_result))
  
  df %>% 
    group_by(prob) %>% 
    summarize(
      win_pct = sum(home_win) / n(),
      nsize = n()
    ) %>% 
    mutate(
      auc_result = auc_result,
      K = K
    )
}
```

```{r}
# Run models
k_results <- map_dfr(seq(16, 40, by = 1), k_testing)

saveRDS(k_results, str_c("other_data/k_results_", today(), ".Rdata"))
```

```{r}
# AUC by k-value
k_results %>% 
  distinct(auc_result, K) %>% 
  ggplot(aes(x = K, y = auc_result)) +
  geom_point() +
  geom_line()
```

```{r}
# Weighted mean absolute error by probability (rounded to 1 digit)
k_results %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(K) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = K, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2)
```

```{r}
# Plot results
k_results %>% 
  filter(K %in% c(20, 21, 22, 23, 24, 25, 35)) %>% 
  mutate(K = as.factor(K)) %>% 
  ggplot(aes(x = prob, y = win_pct, color = K, group = K)) +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1))
```

```{r}

```
