---
title: "SFPA Individual Ratings K Optimization"
author: "Skip Perry"
date: "3/14/2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(lubridate)
library(pROC)
```

```{r}
# Data frame of players and team names in Spring 2019 - helper for next helper function
players_by_team_19 <- 
  bind_rows(
    results_19_no_forfeits %>% distinct(home_team, home) %>% transmute(player = home, team = home_team),
    results_19_no_forfeits %>% distinct(away_team, away) %>% transmute(player = away, team = away_team)
  ) %>% 
    distinct() %>% 
    arrange(team, player)

# Helper function to add team names to a data frame containing a column for player
append_team_names <- function(df) {
  df %>% 
    full_join(players_by_team_19, by = "player")
}

# Helper function to get a player's rating
get_rating <- function(player_name, ratings_df) {
  ratings_df %>% 
    filter(player == player_name) %>% 
    pull(rating)
}

# Helper function to get player list
full_player_list <- function(df) {
  bind_rows(
    df %>% select(home) %>% transmute(player = home), 
    df %>% select(away) %>% transmute(player = away)
  ) %>% 
    distinct(player) %>% 
    arrange(player)
}

# Helper function for ELO match win probability
match_win_probability <- function(player_of_interest, home_rating, away_rating, home_advantage) {
  if (player_of_interest == "home") {
    prob <- 1 / (1 + 10 ^ ((away_rating - (home_rating + home_advantage)) / 400))
  } else {
    prob <- 1 / (1 + 10 ^ (((home_rating + home_advantage) - away_rating) / 400))
  }
  prob
}
```

```{r}
# Function for simulating results at different levels of K
k_testing <- function(K) {
  print(str_c("Starting k = ", K))
  
  elo_ratings <-
    full_player_list(train) %>% 
    mutate(rating = 1500)
  
  train_internal <- train
  
  for (i in 1:nrow(train_internal)) {
    player1 <- train_internal$home[i]
    player2 <- train_internal$away[i]
    player1_rating <- get_rating(player1, elo_ratings)
    player2_rating <- get_rating(player2, elo_ratings)
    train_internal$p1_start_rating[i] <- player1_rating
    train_internal$p2_start_rating[i] <- player2_rating
    player1_expected <-
      match_win_probability(
        player_of_interest = "home", home_rating = player1_rating, away_rating = player2_rating,
        home_advantage = home_advantage
      )
    player2_expected <-
      match_win_probability(
        player_of_interest = "away", home_rating = player1_rating, away_rating = player2_rating,
        home_advantage = home_advantage
      )
    winner <- train_internal$game_winner[i]
    S1 <- ifelse(winner == "home", 1, 0)
    S2 <- ifelse(winner == "home", 0, 1)
    player1_rating_new = player1_rating + K * (S1 - player1_expected)
    player2_rating_new = player2_rating + K * (S2 - player2_expected)
    elo_ratings$rating[elo_ratings$player == player1] <- player1_rating_new
    elo_ratings$rating[elo_ratings$player == player2] <- player2_rating_new
    train_internal$p1_end_rating[i] <- player1_rating_new
    train_internal$p2_end_rating[i] <- player2_rating_new
  }
    
  df <- 
    test %>% 
    select(home_player = home, away_player = away, game_winner) %>% 
    inner_join(
      elo_ratings %>% transmute(home_player = player, home_rating = rating),
      by = "home_player"
    ) %>% 
    inner_join(
      elo_ratings %>% transmute(away_player = player, away_rating = rating),
      by = "away_player"
    ) %>% 
    mutate(
      home_win = if_else(game_winner == "home", 1, 0),
      home_win_prob = 1 / (1 + 10 ^ ((away_rating - (home_rating + home_advantage)) / 400)),
      prob = round(home_win_prob, 1)
    ) %>% 
    arrange(home_win_prob)
  
  auc_result <- as.numeric(auc(roc(df %>% pull(home_win), df %>% pull(home_win_prob))))

  print(str_c("AUC = ", auc_result))
  
  df %>% 
    group_by(prob) %>% 
    summarize(
      win_pct = sum(home_win) / n(),
      nsize = n()
    ) %>% 
    mutate(
      auc_result = auc_result,
      K = K
    )
}
```

```{r}
# Run models
k_results <- map_dfr(seq(6, 46, by = 1), k_testing)

saveRDS(k_results, str_c("other_data/k_results_", today(), ".Rdata"))
```

```{r}
# AUC by k-value
k_results %>% 
  distinct(auc_result, K) %>% 
  ggplot(aes(x = K, y = auc_result)) +
  geom_point() +
  geom_line()
```

```{r}
# Weighted mean absolute error by probability (rounded to 1 digit)
k_results %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(K) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = K, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2)
```

```{r}
k_results %>% 
  filter(K %in% seq(20, 24, 1)) %>% 
  mutate(K = as.factor(K)) %>% 
  ggplot(aes(x = prob, y = win_pct, color = K, group = K)) +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1))
```

```{r}
df %>% 
  group_by(prob) %>% 
  summarize(
    pct_correct = sum(home_win) / n(),
    total = n()
  ) %>% 
  filter(total > 60) %>% 
  mutate(diff = abs(prob - pct_correct)) %>% 
  pull(diff) %>% 
  sum()
```