---
title: "SFPA Fargo Ratings v.3"
author: "Skip Perry"
date: "March 2019"
output: github_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(lubridate)
library(pROC)

source("02_data_clean.R")

full_data <- 
  results_no_forfeits %>% 
  select(-c(forfeit:t2_end_rating))
```

```{r}

```

```{r}
player_record <- function(player_of_interest, results_df) {
  results_df %>% 
  filter(away == player_of_interest | home == player_of_interest) %>% 
  mutate(
    player = player_of_interest,
    opponent = if_else(home == player_of_interest, away, home),
    game_result = case_when(
      home == player_of_interest & game_winner == "home" ~ "W",
      away == player_of_interest & game_winner == "away" ~ "W",
      TRUE ~ "L"
    )
  )
}

append_ratings_to_player_record <- function(player_record, current_ratings) {
  player_record %>% 
    inner_join(
      current_ratings %>% transmute(player, player_rating = rating), 
      by = "player"
    ) %>% 
    inner_join(
      current_ratings %>% transmute(opponent = player, opponent_rating = rating), 
      by = "opponent"
    )
}

generate_robustness <- function(results_df, games_to_full_robustness = 20) {
  robustness <- 
    bind_rows(results_df %>% select(player = home), results_df %>% select(player = away)) %>% 
    distinct() %>% 
    arrange(player) %>% 
    mutate(robustness = NA_integer_)
  
  for (i in 1:nrow(robustness)) {
    robustness$robustness[i] <- player_record(robustness$player[i], results_df) %>% count() %>% pull()
  }
  
  robustness %>% 
    transmute(
      player, 
      R = if_else(robustness > games_to_full_robustness, 1, robustness / games_to_full_robustness)
    )
}

generate_latest_match_date <- function(results_df) {
  latest_match_date <- 
    bind_rows(results_df %>% select(player = home), results_df %>% select(player = away)) %>% 
      distinct() %>% 
      arrange(player) %>% 
      mutate(latest_match_date = today() - 1500)
  
  for (i in 1:nrow(latest_match_date)) {
      latest_match_date$latest_match_date[i] <- 
        player_record(latest_match_date$player[i], results_df) %>% pull(match_date) %>% max()
  }
  
  latest_match_date
}

updated_fargo_rating <- function(
  player_of_interest, gamma_prior = 1, results_df, current_ratings, decay_factor = 1500, robustness_df,
  latest_match_date_df
) {
  b <- ifelse(gamma_prior > 1, (gamma_prior - 1) / 500, 0)
  latest_match_date <- 
    latest_match_date_df %>% filter(player == player_of_interest) %>% pull(latest_match_date)
  
  player_record(player_of_interest = player_of_interest, results_df = results_df) %>% 
    append_ratings_to_player_record(current_ratings) %>% 
    left_join(robustness_df %>% transmute(opponent = player, R), by = "opponent") %>% 
    mutate(
      A = 1 / (player_rating + opponent_rating),
      W = if_else(game_result == "W", 1, 0),
      latest_match_date = latest_match_date,
      time_decay = (decay_factor - as.numeric(latest_match_date - match_date)) / decay_factor
    ) %>% 
    summarize(A = sum(A * time_decay * R), W = sum(W * time_decay * R)) %>% 
    mutate(rating = (gamma_prior - 1 + W) / (b + A)) %>% 
    pull(rating)
}
```

```{r}
date_loop <- 
  full_data %>% 
  select(match_date) %>% 
  filter(match_date < "2018-07-01") %>% 
  distinct() %>% 
  pull()

run_fargo <- function(as_of_match_date) {
  print(str_c("Starting process for matches as of ", as_of_match_date))
  
  df <-
    full_data %>% 
    filter(match_date <= as_of_match_date)
  
  robustness_df <- generate_robustness(df)
  latest_match_date_df <- generate_latest_match_date(df)
  
  current_fargo_ratings <- 
    bind_rows(df %>% select(player = home), df %>% select(player = away)) %>% 
    distinct() %>%
    arrange(player) %>% 
    mutate(rating = 500)
  
  mean_abs_diff <- 10000
  n_iter <- 0
  
  while (mean_abs_diff > 100) {
    n_iter <- n_iter + 1
    old_ratings <- current_fargo_ratings %>% pull(rating)
    for (i in 1:nrow(current_fargo_ratings)) {
      player_of_interest <- current_fargo_ratings$player[i]
      current_fargo_ratings$rating[i] <- updated_fargo_rating(
        player_of_interest = player_of_interest, 
        gamma_prior = 2.5, 
        results_df = df, 
        current_ratings = current_fargo_ratings,
        decay_factor = 1500,
        robustness_df = robustness_df,
        latest_match_date_df = latest_match_date_df
      )
    }
    new_ratings <- current_fargo_ratings %>% pull(rating)
    #print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
    mean_abs_diff <- sum(abs(old_ratings - new_ratings))
  }
  print(str_c("Converged in ", n_iter, " iterations"))
  
  current_fargo_ratings %>% 
    mutate(match_date = df %>% slice(n()) %>% pull(match_date))
}

df_test_3 <- 
  bind_rows(
    map_dfr(date_loop, run_fargo),
    df_test_3
  )
```

```{r}
df_test_3 %>% 
  group_by(match_date) %>% 
  summarize(mean = mean(rating))
```

```{r}
team_members <- function(team_name) {
  bind_rows(
    full_data %>% filter(season == "Spring 2019", home_team == team_name) %>% select(player = home),
    full_data %>% filter(season == "Spring 2019", away_team == team_name) %>% select(player = away)
  ) %>% 
    distinct(player) %>% 
    arrange(player) %>% 
    pull()
}

plot_multiple_player_ratings <- function(player_list) {
  df_test_3 %>% 
    filter(player %in% player_list) %>% 
    ggplot(aes(x = match_date, y = rating, color = player, group = player)) +
    geom_hline(yintercept = 500, size = 2, color = "white") +
    geom_point(size = 1) +
    geom_line() +
    labs(
      x = "Match Date", y = "Rating"
    ) +
    theme(
      legend.title = element_blank(),
      plot.title = element_text(hjust = 0.5),
      legend.position = "bottom",
      legend.text = element_text(size = 10)
    )
}

plot_multiple_player_ratings(player_list = team_members("Tandy Tokers"))
plot_multiple_player_ratings(player_list = team_members("Route 101 Rawhides"))
plot_multiple_player_ratings(player_list = team_members("Cafe Strikes Again"))
plot_multiple_player_ratings(player_list = team_members("Lucky Horseshoe Caballeros"))
```

```{r}
df_test_2 %>% 
  filter(rating < 1500) %>% 
  ggplot(aes(x = match_date, y = rating, group = player)) +
  geom_line(alpha = 0.2)
```

```{r}
sdevs <- 
  df_test_3 %>% 
  group_by(player) %>% 
  summarize(sdev = sd(rating))

df_test_3 %>% 
  left_join(sdevs, by = "player") %>% 
  filter(sdev > 120) %>% 
  ggplot(aes(x = match_date, y = rating, group = player, color = player)) +
  geom_line() +
  geom_point(size = 1)
```

```{r}
top_10_players <- 
  df_test_3 %>% 
  filter(match_date > "2018-05-01") %>% 
  arrange(desc(rating)) %>% 
  group_by(match_date) %>% 
  mutate(rank = row_number()) %>% 
  ungroup() %>% 
  filter(rank < 5) %>% 
  select(player) %>% 
  distinct()

df_test_3 %>% 
  filter(match_date > "2018-05-01") %>% 
  arrange(desc(rating)) %>% 
  group_by(match_date) %>% 
  mutate(rank = row_number()) %>% 
  ungroup() %>% 
  inner_join(top_10_players, by = "player") %>% 
  ggplot(aes(x = match_date, y = rank, group = player, color = player)) +
  geom_line() +
  geom_point(size = 1) +
  coord_cartesian(ylim = c(0, 25))
```

```{r}
lagged_ratings <- 
  df_test_3 %>% 
  group_by(player) %>% 
  mutate(rating = replace_na(lag(rating, n = 1), 500)) %>% 
  arrange(player, match_date) %>% 
  ungroup()

lagged_ratings %>% 
  filter(player == "Jerry Ervin")
```

```{r}
test_set_with_win_probs <- 
  full_data %>% 
  filter(season == "Spring 2019") %>% 
  left_join(lagged_ratings %>% transmute(match_date, home = player, home_rating = rating), by = c("match_date", "home")) %>% 
  left_join(lagged_ratings %>% transmute(match_date, away = player, away_rating = rating), by = c("match_date", "away"))  %>% 
  mutate(
    home_win = if_else(game_winner == "home", 1, 0),
    home_win_prob = home_rating / (home_rating + away_rating),
    prob = round(home_win_prob, 1)
  )

test_set_with_win_probs %>% 
  group_by(prob) %>% 
  summarize(
    wins = sum(home_win),
    nsize = n(),
    win_pct = wins / nsize
  )

match_results <- test_set_with_win_probs %>% pull(home_win)
match_probabilities <- test_set_with_win_probs %>% pull(home_win_prob)

auc_results <- as.numeric(auc(roc(match_results, match_probabilities)))

log_loss_results <- 
  -1 / length(match_results) * sum(
    match_results * log(match_probabilities) + 
      (1 - match_results) * log(1 - match_probabilities)
  )
```


```{r}
# Needs from out of function:
# cv_folds number
# full_data, robustness, latest_match_date data frames
cv_prior_testing <- function(gamma_prior) {
  auc_results <- rep(0, cv_folds)
  log_loss_results <- rep(0, cv_folds)
  accuracy_results <- rep(0, cv_folds)
  
  probs_vs_wins <- 
    tribble(
      ~prob, ~wins, ~nsize
    )
  
  decay_factor <- 1500
  
  robustness_df <- generate_robustness(full_data)
  latest_match_date_df <- generate_latest_match_date(full_data)

  print(str_c("Testing gamma prior ", gamma_prior))
  
  for (c in 1:cv_folds) {
    print(str_c("CV fold ", c))
    train_data <- full_data %>% filter(cv != c)
    test_data <- full_data %>% filter(cv == c)
    
    current_fargo_ratings <- 
      bind_rows(train_data %>% select(player = home), train_data %>% select(player = away)) %>% 
      distinct() %>%
      arrange(player) %>% 
      mutate(rating = 500)
    
    mean_abs_diff <- 10000
    n_iter <- 0
    
    while (mean_abs_diff > 100) {
      n_iter <- n_iter + 1
      old_ratings <- current_fargo_ratings %>% pull(rating)
      for (i in 1:nrow(current_fargo_ratings)) {
        player_of_interest <- current_fargo_ratings$player[i]
        current_fargo_ratings$rating[i] <- updated_fargo_rating(
          player_of_interest = player_of_interest, 
          gamma_prior = gamma_prior, 
          results_df = train_data, 
          current_ratings = current_fargo_ratings,
          decay_factor = decay_factor,
          robustness_df = robustness_df,
          latest_match_date_df = latest_match_date_df
        )
      }
      new_ratings <- current_fargo_ratings %>% pull(rating)
      print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
      mean_abs_diff <- sum(abs(old_ratings - new_ratings))
    }
    print(str_c("Converged in ", n_iter, " iterations"))
    
    test_set_with_win_probs <-
      test_data %>% 
        transmute(player = home, opponent = away, game_winner) %>% 
        append_ratings_to_player_record(current_fargo_ratings)  %>% 
        mutate(
          player_win = if_else(game_winner == "home", 1, 0),
          player_win_prob = player_rating / (player_rating + opponent_rating),
          prob = round(player_win_prob, 1)
        )
    
    match_results <- test_set_with_win_probs %>% pull(player_win)
    match_probabilities <- test_set_with_win_probs %>% pull(player_win_prob)
    
    auc_results[c] <- as.numeric(auc(roc(match_results, match_probabilities)))
    
    log_loss_results[c] <- 
      -1 / length(match_results) * sum(
        match_results * log(match_probabilities) + 
          (1 - match_results) * log(1 - match_probabilities)
      )
    
    accuracy_results[c] <- sum(match_results == round(match_probabilities)) / length(match_results)
    
    probs_vs_wins_cv <- 
      test_set_with_win_probs %>% 
        group_by(prob) %>% 
        summarize(
          wins = sum(player_win),
          nsize = n()
        )
    
    probs_vs_wins <- 
      bind_rows(
        probs_vs_wins,
        probs_vs_wins_cv
      )
  }
  
  probs_vs_wins %>% 
    group_by(prob) %>% 
    summarize(
      wins = sum(wins),
      nsize = sum(nsize)
    ) %>% 
    mutate(
      win_pct = wins / nsize,
      auc = mean(auc_results),
      log_loss = mean(log_loss_results),
      accuracy = mean(accuracy_results),
      gamma_prior = gamma_prior
    )
}
```

```{r}


cv_testing_4 <- map_dfr(c(1.1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5), cv_prior_testing)

map_dfr(2.5, cv_prior_testing)
```

```{r}
#cv_testing_3 <- 
#  map_dfr(c(4, 5), cv_prior_testing)

# saveRDS(cv_testing_3, "other_data/cv_testing_320.Rdata")
saveRDS(cv_testing_4, "other_data/cv_testing_321.Rdata")
```

```{r}
cv_testing_3 <- readRDS("other_data/cv_testing_320.Rdata")

cv_testing_4 %>% 
  #filter(gamma_prior > 2.5, gamma_prior < 5.5) %>% 
  mutate(gamma_prior = as.factor(gamma_prior)) %>% 
  ggplot(aes(x = prob, y = win_pct, color = gamma_prior, group = gamma_prior)) +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, color = "white", size = 2) +
  geom_point() +
  geom_line() +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(
    title = "Predicted Probability vs. Win Percentage"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
cv_testing_4 %>% 
  mutate(diff = abs(win_pct - prob)) %>% 
  group_by(gamma_prior) %>% 
  summarize(err = sum(diff * nsize / sum(nsize))) %>% 
  ggplot(aes(x = gamma_prior, y = err)) + 
  geom_point() + 
  geom_line() +
  geom_hline(yintercept = 0, color = "white", size = 2) +
  labs(
    title = "Weighted MAE Across Gamma Priors"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
cv_testing_4 %>% 
  distinct(auc, log_loss, accuracy, gamma_prior) %>% 
  gather(metric, value, -gamma_prior) %>% 
  ggplot(aes(x = gamma_prior, y = value, color = metric, group = metric)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Performance Metrics Comparison"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5)
  )
```

```{r}
# NEED TO UPDATE

# Select best gamma prior and run ratings on full data set
gamma_prior <- 2.5

final_fargo_ratings <- 
  bind_rows(full_data %>% select(player = home), full_data %>% select(player = away)) %>% 
  distinct() %>%
  arrange(player) %>% 
  mutate(rating = 500)

mean_abs_diff <- 10000
decay_factor <- 1500
n_iter <- 0

while (mean_abs_diff > 50) {
  n_iter <- n_iter + 1
  old_ratings <- final_fargo_ratings %>% pull(rating)
  for (i in 1:nrow(final_fargo_ratings)) {
    player_of_interest <- final_fargo_ratings$player[i]
    final_fargo_ratings$rating[i] <- updated_fargo_rating(
      player_of_interest = player_of_interest, 
      gamma_prior = gamma_prior, 
      results_df = full_data, 
      current_ratings = final_fargo_ratings,
      decay_factor = decay_factor,
      robustness_df = robustness
    )
  }
  new_ratings <- final_fargo_ratings %>% pull(rating)
  print(str_c("Mean absolute difference: ", sum(abs(old_ratings - new_ratings))))
  mean_abs_diff <- sum(abs(old_ratings - new_ratings))
}
print(str_c("Converged in ", n_iter, " iterations"))

final_fargo_ratings %>% 
  arrange(desc(rating))

saveRDS(final_fargo_ratings, "other_data/fargo_ratings_321.Rdata")
```


```{r}
results_no_forfeits %>% 
  filter(away == "Jonathan")
```

